create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  service_name text not null,
  service_price text not null,
  service_date date not null,
  time_slot text not null,
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  service_address text not null,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'cancelled', 'completed')),
  created_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text not null unique,
  price text not null,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

insert into public.services (name, price, sort_order)
values
  ('ทำความสะอาดบ้าน', 'เริ่มต้น 45 บาท/ตร.ม.', 0),
  ('ทำความสะอาดบ้านคอนโด', 'เริ่มต้น 45 บาท/ตร.ม.', 1),
  ('ทำความสะอาดสำนักงาน', 'เริ่มต้น 45 บาท/ตร.ม.', 2),
  ('Big Cleaning', 'เริ่มต้น 45 บาท/ตร.ม.', 3),
  ('ขอโปไซน์', 'เริ่มต้น 1,500 บาท', 4),
  ('หลังน้ำท่วม', 'เริ่มต้น 45 บาท/ตร.ม.', 5)
on conflict (name) do nothing;

alter table public.services enable row level security;

create unique index if not exists one_active_booking_per_slot
  on public.bookings (service_date, time_slot)
  where status in ('pending', 'confirmed');

create or replace function public.get_unavailable_booking_slots(target_date date)
returns table (time_slot text)
language sql
security definer
set search_path = public
stable
as $$
  select b.time_slot
  from public.bookings b
  where b.service_date = target_date
    and b.status in ('pending', 'confirmed');
$$;

revoke all on function public.get_unavailable_booking_slots(date) from public;
grant execute on function public.get_unavailable_booking_slots(date) to authenticated;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  full_name text,
  phone text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

insert into public.profiles (id, username, full_name, phone)
select id, raw_user_meta_data ->> 'username', raw_user_meta_data ->> 'full_name', raw_user_meta_data ->> 'phone'
from auth.users
on conflict (id) do nothing;

alter table public.profiles enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

drop policy if exists "Anyone authenticated can view active services" on public.services;
create policy "Anyone authenticated can view active services"
  on public.services for select
  to authenticated
  using (is_active or public.is_admin());

drop policy if exists "Admins can insert services" on public.services;
create policy "Admins can insert services"
  on public.services for insert
  to authenticated
  with check (public.is_admin());

drop policy if exists "Admins can update services" on public.services;
create policy "Admins can update services"
  on public.services for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Admins can delete services" on public.services;
create policy "Admins can delete services"
  on public.services for delete
  to authenticated
  using (public.is_admin());

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username, full_name, phone)
  values (
    new.id,
    new.raw_user_meta_data ->> 'username',
    new.raw_user_meta_data ->> 'full_name',
    new.raw_user_meta_data ->> 'phone'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

drop policy if exists "Users can view their own profile" on public.profiles;
create policy "Users can view their own profile"
  on public.profiles for select
  to authenticated
  using (auth.uid() = id or public.is_admin());

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

create or replace function public.reject_past_booking()
returns trigger
language plpgsql
as $$
begin
  if new.service_date < current_date then
    raise exception 'ไม่สามารถจองย้อนหลังได้';
  end if;
  return new;
end;
$$;

create or replace function public.protect_booking_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is not null and not public.is_admin() then
    if old.status <> 'pending' then
      raise exception 'รายการนี้ยืนยันแล้ว ไม่สามารถแก้ไขได้';
    end if;
    if new.status <> old.status then
      raise exception 'ผู้ใช้ไม่สามารถเปลี่ยนสถานะรายการจองได้';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists bookings_reject_past_date on public.bookings;
create trigger bookings_reject_past_date
  before insert or update on public.bookings
  for each row execute function public.reject_past_booking();

drop trigger if exists bookings_protect_changes on public.bookings;
create trigger bookings_protect_changes
  before update on public.bookings
  for each row execute function public.protect_booking_changes();

alter table public.bookings enable row level security;

drop policy if exists "Users can view their own bookings" on public.bookings;
create policy "Users can view their own bookings"
  on public.bookings for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can create their own bookings" on public.bookings;
create policy "Users can create their own bookings"
  on public.bookings for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own bookings" on public.bookings;
create policy "Users can update their own bookings"
  on public.bookings for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can cancel their own bookings" on public.bookings;
create policy "Users can cancel their own bookings"
  on public.bookings for delete
  to authenticated
  using (auth.uid() = user_id and status = 'pending');

drop policy if exists "Admins can view all bookings" on public.bookings;
create policy "Admins can view all bookings"
  on public.bookings for select
  to authenticated
  using (public.is_admin());

drop policy if exists "Admins can update all bookings" on public.bookings;
create policy "Admins can update all bookings"
  on public.bookings for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- Run once after creating your own account to grant admin access:
-- update public.profiles set role = 'admin' where id = (select id from auth.users where email = 'your-email@example.com');