create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  service_name text not null,
  service_price text not null,
  service_date date not null,
  time_slot text not null,
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  service_address text not null,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'cancelled', 'completed')),
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  full_name text,
  phone text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

insert into public.profiles (id, username, full_name, phone)
select id, raw_user_meta_data ->> 'username', raw_user_meta_data ->> 'full_name', raw_user_meta_data ->> 'phone'
from auth.users
on conflict (id) do nothing;

alter table public.profiles enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username, full_name, phone)
  values (
    new.id,
    new.raw_user_meta_data ->> 'username',
    new.raw_user_meta_data ->> 'full_name',
    new.raw_user_meta_data ->> 'phone'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

drop policy if exists "Users can view their own profile" on public.profiles;
create policy "Users can view their own profile"
  on public.profiles for select
  to authenticated
  using (auth.uid() = id or public.is_admin());

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

create or replace function public.reject_past_booking()
returns trigger
language plpgsql
as $$
begin
  if new.service_date < current_date then
    raise exception 'ไม่สามารถจองย้อนหลังได้';
  end if;
  return new;
end;
$$;

drop trigger if exists bookings_reject_past_date on public.bookings;
create trigger bookings_reject_past_date
  before insert or update on public.bookings
  for each row execute function public.reject_past_booking();

alter table public.bookings enable row level security;

drop policy if exists "Users can view their own bookings" on public.bookings;
create policy "Users can view their own bookings"
  on public.bookings for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can create their own bookings" on public.bookings;
create policy "Users can create their own bookings"
  on public.bookings for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own bookings" on public.bookings;
create policy "Users can update their own bookings"
  on public.bookings for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can cancel their own bookings" on public.bookings;
create policy "Users can cancel their own bookings"
  on public.bookings for delete
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Admins can view all bookings" on public.bookings;
create policy "Admins can view all bookings"
  on public.bookings for select
  to authenticated
  using (public.is_admin());

drop policy if exists "Admins can update all bookings" on public.bookings;
create policy "Admins can update all bookings"
  on public.bookings for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- Run once after creating your own account to grant admin access:
-- update public.profiles set role = 'admin' where id = (select id from auth.users where email = 'your-email@example.com');